version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Define environment variables here if needed
      SPRING_PROFILES_ACTIVE: prod
    restart: always
